language: node_js
node_js:
  - lts/*
services:
  - mongodb
install:
  - npm install
before_script:
  - node app
#  - sudo service mongod start
#  - sudo mongod
script:
  - yarn test
after_success:
  - npm run coverage
