name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [10.x, 12.x, 14.x, 15.x]
            mongodb-version: [4.0, 4.2, 4.4]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run Unit Tests
        run: |
          npm test
          npm run coverage

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
